#**Logistic Regression Implementation**

In [ ]:
#load dataset from default datasets
from sklearn.datasets import load_iris

In [ ]:
dataset = load_iris()

In [ ]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
#import the required libraries
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame(dataset.data, columns = (dataset.feature_names))

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Dataset of 'iris' contains target values as the Iris-Setosa, Iris-Versicolour and Iris-Virginica but we're learning about binary logistic regression where classification are done on only two target values. so, we are removing the Iris-Virginica for further practice.

In [ ]:
#adding the target attribute in dataset
df["target"] = dataset.target

In [ ]:
#binary classification
df = df[df["target"] != 2]

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
df.target.unique() #means there are only two binary output values

array([0, 1])

## Independent and dependent features

In [ ]:
#creating the X and y datasets
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [ ]:
#importing the train and test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 47)

In [ ]:
#importing the logistic regression
from sklearn.linear_model import LogisticRegression

#create the instance
classifier = LogisticRegression()

In [ ]:
#fit the model
classifier.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#predicting with model
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

###confusion matrix, accuracy score and classfication report

In [ ]:
#importing the libraries for performance metrics
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [ ]:
#printing the metrics
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[ 9  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [ ]:
#predict_proba shows how we get the output value
predict_proba = classifier.predict_proba(X_test)
predict_proba

array([[0.97958189, 0.02041811],
       [0.01111708, 0.98888292],
       [0.01630809, 0.98369191],
       [0.0040541 , 0.9959459 ],
       [0.0048114 , 0.9951886 ],
       [0.96528988, 0.03471012],
       [0.98296355, 0.01703645],
       [0.98938532, 0.01061468],
       [0.98419421, 0.01580579],
       [0.98053344, 0.01946656],
       [0.00650262, 0.99349738],
       [0.97422348, 0.02577652],
       [0.08320573, 0.91679427],
       [0.02345043, 0.97654957],
       [0.00573732, 0.99426268],
       [0.02222118, 0.97777882],
       [0.96888588, 0.03111412],
       [0.01883292, 0.98116708],
       [0.06836717, 0.93163283],
       [0.98138098, 0.01861902]])

In [ ]:
y_pred

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
pd.DataFrame({"0th value" : predict_proba[:, 0],
             "1st value" : predict_proba[:, 1],
             "y_pred" : y_pred})

0th value  1st value  y_pred
0    0.979582   0.020418       0
1    0.011117   0.988883       1
2    0.016308   0.983692       1
3    0.004054   0.995946       1
4    0.004811   0.995189       1
5    0.965290   0.034710       0
6    0.982964   0.017036       0
7    0.989385   0.010615       0
8    0.984194   0.015806       0
9    0.980533   0.019467       0
10   0.006503   0.993497       1
11   0.974223   0.025777       0
12   0.083206   0.916794       1
13   0.023450   0.976550       1
14   0.005737   0.994263       1
15   0.022221   0.977779       1
16   0.968886   0.031114       0
17   0.018833   0.981167       1
18   0.068367   0.931633       1
19   0.981381   0.018619       0

### Hyperparameter tuning

####GridSearchCV

In [ ]:
#importing the gridsearch cv
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#create the paramter for gridsearchcv
parameters = {
    "penalty" : ("l1", "l2", "elasticnet", None),
    "C" : [1, 10, 20]
}

In [ ]:
#create the model
clf = GridSearchCV(classifier, param_grid = parameters, cv = 5)

#fit the model for splitting of train data into train and validate data
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [ ]:
#finding the best parameters
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [ ]:
#create the model with best parameter
classifier = LogisticRegression(C = 1, penalty = "l2")

In [ ]:
#fit the model
classifier.fit(X_train, y_train)

LogisticRegression(C=1)

In [ ]:
#prediction
y_pred = classifier.predict(X_test)

In [ ]:
y_pred

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
#printing the metrics
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[ 9  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



####Randomized SearchCV

In [ ]:
#import the model
from sklearn.model_selection import RandomizedSearchCV

#create the instance
random_clf = RandomizedSearchCV(LogisticRegression(),
                                param_distributions = parameters,
                                cv = 5)

In [ ]:
#fit the model
random_clf.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [ ]:
random_clf.best_params_

{'penalty': 'l2', 'C': 10}

In [ ]:
#create the model with best parameter
classifier = LogisticRegression(C = 10, penalty = "l2")

In [ ]:
#fit the model
classifier.fit(X_train, y_train)

LogisticRegression(C=10)

In [ ]:
#prediction
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
#printing the metrics
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[ 9  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## MultiClass Logistic Regression

In [ ]:
#make a prediction with multiclass regression
from sklearn.datasets import make_classification

#define the dataset
X, y = make_classification(n_samples = 1000, n_features = 10,
                           n_informative = 5, n_redundant = 5,
                           n_classes = 3, random_state = 47)

In [ ]:
X

array([[-1.95922940e+00, -1.09721086e+00, -1.51774059e+00, ...,
        -1.31834941e+00,  1.58700722e+00, -5.98368070e-01],
       [ 7.88588259e-01,  4.66464201e-01,  1.09538999e+00, ...,
         1.65040645e-01,  2.06478361e+00, -1.86809638e+00],
       [-1.19900359e+00, -2.36918704e-03, -1.09889832e+00, ...,
        -7.12916074e-01, -7.89659822e-01,  8.55576459e-01],
       ...,
       [ 1.11311709e+00, -2.37015258e+00,  1.10605689e+00, ...,
         3.06465477e+00, -3.20532632e+00,  7.66613248e-01],
       [ 1.71662545e+00, -2.69828041e+00, -1.09187714e+00, ...,
         6.57346087e-01,  1.50084380e+00, -1.38047368e+00],
       [ 3.11721198e+00,  4.99036148e+00,  3.81754035e+00, ...,
         2.28517015e-01,  2.30363269e+00, -2.24221534e+00]])

In [ ]:
y

array([1, 0, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 2, 1, 0, 0, 2, 1, 2, 0,
       0, 0, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 2, 2, 0, 2, 2, 1, 2, 0, 0, 1, 0, 1, 0, 2, 2, 0, 0, 2,
       0, 2, 0, 0, 0, 1, 2, 1, 0, 2, 0, 1, 1, 0, 0, 0, 2, 1, 1, 0, 2, 2,
       1, 0, 0, 1, 1, 0, 2, 1, 2, 1, 1, 1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 0, 0,
       2, 0, 2, 0, 2, 1, 2, 0, 1, 2, 0, 0, 2, 0, 2, 1, 1, 2, 2, 0, 1, 0,
       0, 1, 2, 0, 1, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 2, 2,
       2, 2, 2, 0, 2, 0, 1, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 1, 0,
       1, 1, 0, 2, 0, 0, 2, 1, 1, 2, 0, 1, 0, 2, 1, 0, 0, 0, 1, 2, 2, 2,
       0, 0, 2, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 2, 0, 2, 1, 2, 0, 1, 2, 2, 2, 2, 2, 0, 0, 1, 0, 1, 2, 2, 1, 1,
       2, 1, 2, 1, 2, 0, 1, 1, 1, 2, 2, 1, 1, 2, 0,

### Multinomial for MultiClass Classification

In [ ]:
#define the multinomial model
model = LogisticRegression(multi_class = "multinomial", solver = "lbfgs")

In [ ]:
#split the train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 47)

#fit the model
model.fit(X_train, y_train)

LogisticRegression(multi_class='multinomial')

In [ ]:
#predict the model
y_pred = model.predict(X_test)
y_pred

array([1, 1, 2, 1, 1, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 2, 2, 0,
       1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0,
       1, 1, 1, 1, 1, 2, 0, 2, 0, 2, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 1, 2,
       1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 0, 2, 2, 0, 1, 1, 1, 0,
       1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 2,
       2, 2, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2,
       0, 1, 2, 1, 2, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1,
       1, 1, 2, 0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0,
       1, 2, 0, 0, 1, 1, 0, 2, 1, 1, 2, 0, 0, 2, 0, 1, 0, 2, 0, 1, 1, 1,
       0, 1])

In [ ]:
#finding by probability
model.predict_proba(X_train)

array([[2.63026519e-01, 8.64450178e-02, 6.50528463e-01],
       [4.42292559e-01, 3.58807284e-01, 1.98900157e-01],
       [4.68718990e-01, 4.27578086e-02, 4.88523202e-01],
       ...,
       [3.99986894e-01, 1.03612112e-02, 5.89651895e-01],
       [5.49453068e-01, 1.35377531e-01, 3.15169401e-01],
       [2.58542024e-01, 2.10638826e-04, 7.41247338e-01]])

In [ ]:
#printing the metrics
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[46  6 19]
 [12 60  3]
 [ 8  4 42]]
0.74
              precision    recall  f1-score   support

           0       0.70      0.65      0.67        71
           1       0.86      0.80      0.83        75
           2       0.66      0.78      0.71        54

    accuracy                           0.74       200
   macro avg       0.74      0.74      0.74       200
weighted avg       0.75      0.74      0.74       200



### One Versus Rest (OVR) for MultiClass Classification

In [ ]:
#define the model
model = LogisticRegression(multi_class = "ovr", solver = "lbfgs")

In [ ]:
#split the train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 47)

#fit the model
model.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [ ]:
#predict the model
y_pred = model.predict(X_test)
y_pred

array([1, 1, 2, 1, 1, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 2, 2, 2,
       1, 1, 0, 0, 2, 1, 2, 1, 2, 0, 1, 0, 1, 1, 0, 2, 2, 2, 1, 2, 2, 0,
       1, 1, 1, 1, 1, 2, 0, 2, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 2, 1, 1, 2,
       1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 0, 2, 2, 0, 1, 1, 1, 0,
       1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 2,
       2, 2, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2,
       2, 1, 2, 1, 2, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1,
       1, 1, 2, 0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0,
       1, 2, 0, 0, 1, 1, 0, 2, 1, 1, 2, 0, 0, 2, 0, 1, 0, 2, 0, 1, 1, 1,
       0, 1])

In [ ]:
#finding by probability
model.predict_proba(X_train)

array([[2.25403914e-01, 1.12809924e-01, 6.61786161e-01],
       [3.68912640e-01, 4.47102515e-01, 1.83984845e-01],
       [4.42254868e-01, 4.60546594e-02, 5.11690473e-01],
       ...,
       [4.20268565e-01, 9.19803275e-03, 5.70533402e-01],
       [5.06715849e-01, 1.63928672e-01, 3.29355479e-01],
       [4.35081722e-01, 1.75499016e-04, 5.64742779e-01]])

In [ ]:
#printing the metrics
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))

[[41  6 18]
 [12 60  3]
 [13  4 43]]
0.72
              precision    recall  f1-score   support

           0       0.62      0.63      0.63        65
           1       0.86      0.80      0.83        75
           2       0.67      0.72      0.69        60

    accuracy                           0.72       200
   macro avg       0.72      0.72      0.72       200
weighted avg       0.72      0.72      0.72       200

